language: objective-c
osx_image: xcode10.1
podfile: src/Podfile
xcode_workspace: src/notes.xcworkspace
xcode_scheme: notesTests
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X

before_install:
    - pod repo update
